### ISSUE TITLE
List of allowed chat models should be updated

### ISSUE THREAD

**Issue by cayyya** [BIMSBbioinfo/mergen#5]
I wanted to learn to use mergen just recently and found setupAgent function not working as the list of allowed chat models seems to be obsolete. I've added gpt-4o-mini and gpt-4o to the list and it works now. Would be nice to update the code in general. 
Thank you.
Karel

**Comment by jacqueline-98** [comment]
Hey Karel, thank you for writing us! this is indeed a good point! We have fixed the issue and now all available models should be ready for you to use, and these will be automatically updated!
